### ISSUE TITLE
Question: Where can I find the source code of "devorbitus/vault-spinnaker-dynamic-accounts"

### ISSUE THREAD

**Issue by KeisukeYamashita** [spinnaker-hackathon/vault-spinnaker-dynamic-accounts#3]
@devorbitus  Hi, this guide is awesome! Thanks for sharing it.
I have one question. Where can I find the source code of "devorbitus/vault-spinnaker-dynamic-accounts" in the last section?

Thanks in advance 🙇

**Comment by devorbitus** [comment]
No problem, it's in the docker directory docker/vault-spinnaker-dynamic-accounts/Dockerfile

**Comment by KeisukeYamashita** [comment]
@devorbitus Oh, I've missed it. Thank you for your kind reply 🙇‍♂️
